### ISSUE TITLE
Provide an ltest executable

### ISSUE THREAD

**Issue by cinova** [lfex/ltest#26]
This would provide a convenience for the following:
 * compiling and running all tests
 * compiling and running just one type of tests (e.g., just integration tests)
 * compiling and running just one module

**Comment by arpunk** [comment]
Right now we can use `lfetool test all` to invoke the `ltest` runner. We can use different testing environments aswell.

**Comment by yurrriq** [comment]
I think `rebar3` solves this one too.

**Comment by arpunk** [comment]
@yurrriq You are right. `rebar3` runs all the `EUnit` test cases (written with `ltest`).

**Comment by yurrriq** [comment]
I think this can probably be closed unless `rebar3` support isn't enough.

**Comment by arpunk** [comment]
`rebar3` is enough for this, what is currently missing is being able to run `common_test` suites. 

Code coverage is out of the question and probably a fair warning in the `README` could help newcomers expecting a one-to-one mapping to Erlang tooling.

**Comment by oubiwann** [comment]
yeah, I would definitely be interested in accepting a patch for `common_test` -- I think ltest is a good home for that set of functionality. I might actually use common test if there was Lisply sane, conceptually coherent way of using it ;-)

Not only does `rebar3` mostly solve this, that itself will likely be wrapped by [ltool](https://github.com/lfe-rebar3/ltool) (which is still quite experimental ... in fact, so experimental that I haven't merged the changes that added a `./bin` dir with an `ltool` escriptized executable wrapping `rebar3`).

Closing ...
