### ISSUE TITLE
Provide an option for building only one type of test

### ISSUE THREAD

**Issue by cinova** [lfex/ltest#27]
For large projects with lots of integration tests, for example, it would be nice to just compile unit tests if only unit tests are going to be run.

**Comment by oubiwann** [comment]
This is now done via the rebar3 LFE test plugin:

```
$ rebar3 lfe test -t unit
$ rebar3 lfe test -t integration
$ rebar3 lfe test -t system
$ rebar3 lfe test -t selenium
$ rebar3 lfe test -t all
$ rebar3 lfe test
```

where the last two are the same.
