### ISSUE TITLE
Add support (macros) for Selenium

### ISSUE THREAD

**Issue by cinova** [lfex/ltest#30]
Maybe something that does any standard boilerplate? At the very least probably:
 * a new behaviour
 * a ``(defwebtest ...)`` macro that wraps ``(deftest ...)``

There is an Erlang webdriver here:
 * https://github.com/Quviq/webdrv

Blog post describing it:
 * http://blog.equanimity.nl/blog/2014/03/07/selenium-webdriver-for-erlang/

Selenium webdriver docs:
 * http://docs.seleniumhq.org/docs/03_webdriver.jsp

**Comment by cinova** [comment]
Just submitted a PR for this work.

**Comment by oubiwann** [comment]
This was merged, but then had to be broken out into its own project here:
 * https://github.com/lfex/lse
