### ISSUE TITLE
Feature idea: add test dirs as argument to ltest-runner:all

### ISSUE THREAD

**Issue by jtmoulia** [lfex/ltest#33]
I'd like to be able to configure where `ltest-runner:all/0` searches for test beams. At the moment, I don't think it can be changed from `.eunit/`.

One way to implement this would be to add `ltest-runner:all/1` where its argument is an options proplist (or dict?):

``` scheme
(defun all () (all '()))

(defun all (opts)
  (let ((dirs (proplists:get_value opts 'dirs '(".eunit"))))
  ...))
```

``` scheme
(all '(#(dirs ("_build/test/dir" ".eunit"))))
```

Though, other `ltest-runner` functions would also have to change.

It is a beautiful runner :)

**Comment by oubiwann** [comment]
This is a great idea -- thanks!

Also, glad you like the runner :-) I'm looking forward to integrating it into an LFE-rebar3 plugin ...

**Comment by oubiwann** [comment]
There's a new branch coming for the 1.0 release that changes to the rebar3 approach: providing the rebar3 profile, the apps you want to test, and the test type you want to run. If these are not provided, sane guesses are made for the missing values.
