### ISSUE TITLE
LFE test runner or default EUnit?

### ISSUE THREAD

**Issue by arpunk** [lfex/ltest#53]
Is the [LFE test runner](https://github.com/lfex/ltest#the-lfe-test-runner-) usage encouraged instead of the current EUnit one that `rebar3` ships with?

It looks like it is meant to be used with `lfetool` which is now deprecated in flavor to `rebar3`.

**Comment by oubiwann** [comment]
I've been using the LFE test runner, and I'm switching most of the projects over to use it. It's not designed for use with `lfetool`, however -- it can be used with any Erlang or LFE tool.

In fact, the way in which I'm using it is by making the [lfe-rebar3/test](https://github.com/lfe-rebar3/test) plugin a dependency in a `test` profiler. Then updating the `make check` target to execute this:

```
rebar3 as test lfe test
```

or, if I don't want to run the system, integration, and selenium tests: 

```
rebar3 as test lfe test -t unit
```

All this being said, it's completely up to you :-) I prefer the coloring and output formatting of the test running (and using the rebar3 lfe plugin makes that super-easy). But others may prefer fewer deps and/or be used the the output of `rebar3 eunit` ...
