### ISSUE TITLE
README: Adding ltest to Your Project

### ISSUE THREAD

**Issue by nigelhp** [lfex/ltest#69]
Apologies in advance - I am new to the LFE ecosystem.  I have encountered difficulties with this step, and thought I should raise it for more experienced eyes to consider.

With the `eunit_compile_opts` located as outlined in this section of the README, running `rebar3 eunit` triggers a `rebar3.crashdump` containing:
```
Error: badarg
[]
```
Moving the `eunit_compile_opts` outside of the `deps` block / tuple (as per the example [here](https://github.com/exercism/lfe/blob/dd47dae7fdff7b8b48a11f504a1a86d5a3f69f05/exercises/practice/hello-world/rebar.config#L9)) seems to resolve the issue.

I am using v3.13.3 of `rebar3`.

**Comment by oubiwann** [comment]
Yeah, I noticed that too (when I was updating the project for the LFE 2.0 release.

Fixed up the README!
